name: Update secret periodically
on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:
jobs:
  login:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for custom actions
        id: checkout-repo
        uses: actions/checkout@v2
      - name: Login to Google Apps Script
        id: gas-login
        uses: ./.github/actions/gas_login
        with:
          clasprc_json: ${{ secrets.CLASPRC_JSON }}
      - name: Save the latest .clasprc.json contents if changed
        id: save-latest-clasprc
        env:
          clasprc_json_secret: ${{ secrets.CLASPRC_JSON }}
        if: ${{ env.clasprc_json_secret != steps.gas-login.outputs.latest_clasprc_json }}
        uses: maclarel/actions-set-secret@v/1.9.9
        with:
          name: "CLASPRC_JSON"
          value: ${{ steps.gas-login.outputs.latest_clasprc_json }}
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          environment: production
