name: Update secret periodically
on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Google Apps Script
        id: gas-login
        uses: ./.github/actions/gas_login
